AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VpcCidr:
    Type: String
    Description: Designated IP range for the vpc
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
  VpcName:
    Type: String 
    AllowedPattern: '[A-Za-z]+'
  Environment: 
    Type: String 
    AllowedPattern: '[A-Za-z]+'
    Description: Environment to be provisioned for, will tag all resources with this value
  PublicSubnetOneCidr:
    Type: String 
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Description: Address range for public subnet one
  PublicSubnetTwoCidr:
    Type: String 
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Description: Address range for public subnet two
  PublicSubnetThreeCidr:
    Type: String 
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Description: Address range for public subnet three 
Mappings:
  SubnetForRegion:
    # I am trialling this stack in tokyo region so am only adding ap-northeast-1 for now
    ap-northeast-1:
      AvailabilityZoneOne: "ap-northeast-1a"
      AvailabilityZoneTwo: "ap-northeast-1c"
      AvailabilityZoneThree: "ap-northeast-1d"
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: !Join
          - '-' 
          -
            - !Ref VpcName
            - !Ref Environment
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: !Join
          - '-' 
          -
            - !Ref VpcName
            - !Ref Environment
            - "InternetGateway"
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: VPC
      InternetGatewayId:
        Ref: InternetGateway
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC
      Tags:
      - Key: Name
        Value: !Join
          - '-' 
          -
            - !Ref VpcName
            - !Ref Environment
            - "RouteTable"
  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGateway
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock: !Ref PublicSubnetOneCidr
      AvailabilityZone: !FindInMap [ SubnetForRegion, !Ref "AWS::Region", "AvailabilityZoneOne" ]
      MapPublicIpOnLaunch: 'true'         
      Tags:
      - Key: Name
        Value: !Join
          - '-' 
          -
            - !FindInMap [ SubnetForRegion, !Ref "AWS::Region", "AvailabilityZoneOne" ]
            - !Ref Environment
            - "Public"
  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock: !Ref PublicSubnetTwoCidr
      AvailabilityZone: !FindInMap [ SubnetForRegion, !Ref "AWS::Region", "AvailabilityZoneTwo" ]
      MapPublicIpOnLaunch: 'true'
      Tags:
      - Key: Name
        Value: !Join
          - '-' 
          -
            - !FindInMap [ SubnetForRegion, !Ref "AWS::Region", "AvailabilityZoneTwo" ]
            - !Ref Environment
            - "Public"
  PublicSubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock: !Ref PublicSubnetThreeCidr
      AvailabilityZone: !FindInMap [ SubnetForRegion, !Ref "AWS::Region", "AvailabilityZoneThree" ]
      MapPublicIpOnLaunch: 'true'
      Tags:
      - Key: Name
        Value: !Join
          - '-' 
          -
            - !FindInMap [ SubnetForRegion, !Ref "AWS::Region", "AvailabilityZoneThree" ]
            - !Ref Environment
            - "Public"
